name: Build and Publish API

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./SurveyBasket/SurveyBasket.sln

      - name: Build solution
        run: dotnet build ./SurveyBasket/SurveyBasket.sln --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ./SurveyBasket/SurveyBasket.Api/SurveyBasket.Api.csproj --configuration Release -r win-x64 -p:SelfContained=true -o ./publish/api

      - name: Upload Published API
        uses: actions/upload-artifact@v4
        with:
          name: surveybasket-api
          path: ./publish/api
