name: Build and Publish .NET Web API Artifact

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 👇 Point restore/build/publish to the solution path
      - name: Restore dependencies
        run: dotnet restore ./SurveyBasket/SurveyBasket.sln

      - name: Build
        run: dotnet build ./SurveyBasket/SurveyBasket.sln --no-restore --configuration Release

      - name: Publish application (self-contained)
        run: dotnet publish ./SurveyBasket/SurveyBasket.Api/SurveyBasket.Api.csproj --configuration Release -r win-x64 -p:PublishSingleFile=true -p:SelfContained=true -o ./publish

      - name: Upload publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-api-publish
          path: ./publish
